### ISSUE TITLE
ConcurrentModificationException on disconnect

### ISSUE THREAD

**Issue by NonSwag** [KennyTV/WorldEditSUI#17]
```
[21:09:34 WARN]: [WorldEditSUI] Async task for WorldEditSUI v1.7.3 generated an exception
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095) ~[?:?]
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049) ~[?:?]
	at WorldEditSUI-1.7.3.jar/eu.kennytv.worldeditsui.WorldEditSUIPlugin.drawSelection(WorldEditSUIPlugin.java:324) ~[WorldEditSUI-1.7.3.jar:?]
	at WorldEditSUI-1.7.3.jar/eu.kennytv.worldeditsui.WorldEditSUIPlugin.drawSelection(WorldEditSUIPlugin.java:305) ~[WorldEditSUI-1.7.3.jar:?]
	at WorldEditSUI-1.7.3.jar/eu.kennytv.worldeditsui.WorldEditSUIPlugin.updateSelections(WorldEditSUIPlugin.java:275) ~[WorldEditSUI-1.7.3.jar:?]
	at WorldEditSUI-1.7.3.jar/eu.kennytv.worldeditsui.WorldEditSUIPlugin.lambda$runRepeatedAsync$2(WorldEditSUIPlugin.java:148) ~[WorldEditSUI-1.7.3.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.6.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

**Comment by NonSwag** [comment]
Thanks for fixing it :+1:
