### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by John-H-Smith** [KennyTV/WorldEditSUI#4]
I get this StackTrace without changing anything:
``Server` thread/ERROR]: Error occurred while enabling WorldEditSUI v1.6.1 (Is it up to date?)
java.lang.NullPointerException: null
	at eu.kennytv.worldeditsui.Settings.loadSettings(Settings.java:78) ~[WorldEditSUI-1.6.1.jar:?]
	at eu.kennytv.worldeditsui.Settings.<init>(Settings.java:66) ~[WorldEditSUI-1.6.1.jar:?]
	at eu.kennytv.worldeditsui.WorldEditSUIPlugin.onEnable(WorldEditSUIPlugin.java:95) ~[WorldEditSUI-1.6.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot_server.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot_server.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot_server.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot_server.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot_server.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot_server.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot_server.jar:git-Spigot-798ea6a-2012f1e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot_server.jar:git-Spigot-798ea6a-2012f1e]
	at java.lang.Thread.run(Thread.java:835) [?:?]``

The boolean in the config file is false.

**Comment by kennytv** [comment]
Did you update from a version prior to 1.6? If so, you have to delete/save and rename your old config for it to create a new one with updated fields

**Comment by kennytv** [comment]
^ See the above
