### ISSUE TITLE
WorldEditSUI fails to load into Spigot 1.15.2 (java.lang.NoClassDefFoundError)

### ISSUE THREAD

**Issue by jordammit** [KennyTV/WorldEditSUI#6]
Server log:
```
[03:18:57] [Server thread/INFO]: [WorldEditSUI] Enabling WorldEditSUI v1.6.1
[03:18:57] [Server thread/INFO]: [WorldEditSUI] Plugin by KennyTV
[03:18:57] [Server thread/ERROR]: Error occurred while enabling WorldEditSUI v1.6.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at eu.kennytv.worldeditsui.WorldEditSUIPlugin.onEnable(WorldEditSUIPlugin.java:105) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Bukkit-fc24934]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343) [spigot-1.15.2.jar:git-Bukkit-fc24934]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:431) [spigot-1.15.2.jar:git-Bukkit-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:450) [spigot-1.15.2.jar:git-Bukkit-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.2.jar:git-Bukkit-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:448) [spigot-1.15.2.jar:git-Bukkit-fc24934]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:261) [spigot-1.15.2.jar:git-Bukkit-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:762) [spigot-1.15.2.jar:git-Bukkit-fc24934]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.15.2.jar:git-Bukkit-fc24934]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.15.2.jar:git-Bukkit-fc24934]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 10 more
```

I was running a server on 1.14.3 a while back and had no issues with the then-current version (1.5.2). After setting up a completely new server (no leftover files at all) and using both newest versions of WESUI and Spigot 1.15.2, I get this error and am unable to see particles or set permissions (rather, LuckPerms sets them but does not recognize that they exist).

Other plugins used:
AdvancedTeleport 5.0.14
BetterSleeping 2.6.0
Dynmap 3.0~beta-10
EssentialsX 2.17.2.12
EssentialsXChat ^
EssentialsXSpawn ^
ItemRecycler 1.2.6
LuckPerms 5.0.72
MineableSpawners 2.0.8
Minepacks 2.3.4
MobsToEggs 1.5.3-1
SilkChests 2.2.0
WorldEdit 7.1.0
WorldEditSUI 1.6.1
WorldGuard 7.0.2

**Comment by jordammit** [comment]
Solved, moved to PaperSpigot and worked immediately first try. Don't know what the deal with that was. Hopefully Paper is a good experience.

**Comment by kennytv** [comment]
Sounds like you accidentally ran CraftBukkit? Else I can't think of why md's ChatComponents wouldn't be inside the jar. Anyways, Paper has a lot of improvements to performance and stability, I don't think you will regret the switch :p
