### ISSUE TITLE
Selection particles not drawn for self, or others.

### ISSUE THREAD

**Issue by HcNguyen111** [KennyTV/WorldEditSUI#7]
First selection worked (flame particle drawn), all subsequent selections kept getting the below exception (the exception also repeats in console until selections are cleared).

```
Paper #173
WorldEditSU v1.7
```

Customised configurations:
```
max-ping: -1
persistent-toggles: true
send-particles-to-all:
  enabled: true
```

Exception Log:
```
[13:25:47 WARN]: [WorldEditSUI] Plugin WorldEditSUI v1.7 generated an exception while executing task 34
java.lang.NullPointerException: null
	at eu.kennytv.worldeditsui.util.ParticleHelper.canSeeOtherParticles(ParticleHelper.java:66) ~[?:?]
	at eu.kennytv.worldeditsui.util.ParticleHelper.playEffectToAll(ParticleHelper.java:58) ~[?:?]
	at eu.kennytv.worldeditsui.util.ParticleHelper.playEffectToAll(ParticleHelper.java:48) ~[?:?]
	at eu.kennytv.worldeditsui.WorldEditSUIPlugin.drawSelection(WorldEditSUIPlugin.java:283) ~[?:?]
	at eu.kennytv.worldeditsui.WorldEditSUIPlugin.updateSelections(WorldEditSUIPlugin.java:263) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-173]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-173]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-173]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
```

**Comment by HcNguyen111** [comment]
Closed. Issue no longer present with Paper #174.

Paper #174 Change Log:
[https://papermc.io/ci/job/Paper-1.15/174/changes](https://papermc.io/ci/job/Paper-1.15/174/changes)

**Comment by HcNguyen111** [comment]
Reopened, sigh.

Issue still present. Paper #174 did NOT resolve.

**Comment by kennytv** [comment]
Yep, it's an oversight on my part. It will be fixed in another release later today.
Workaround until then: Disable `send-particles-to-all`

**Comment by HcNguyen111** [comment]
Thanks for v1.7.1. Works. Also appreciate the other improvements - advanced grid looks great.
